services:
  stationeers-server:
    container_name: stationeers-server-ui
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile
    image: stationeersserverui:latest
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 16G
        reservations:
          cpus: '4'
          memory: 8G
    ports:
      - "8443:8443"
      - "27016:27016/udp"
      - "27016:27016/tcp"
      - "27015:27015/udp"
      - "27015:27015/tcp"
    volumes:
      - app-data:/app
      - ./saves:/app/saves:rw
      - ./SSUI:/app/SSUI:rw
    restart: unless-stopped

volumes:
  app-data:
